---
apiVersion: v1
kind: Pod 
metadata: 
  name: nginx_pod
spec:
  containers:
  - name: nginx
      image: 471112902003.dkr.ecr.ap-south-1.amazonaws.com/nginx:latest
      ports: 
      - containerPort: 80
